name: CI Pipeline Practice

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Build Step
        run: echo "Building application..."

      - name: Run Test Step
        run: echo "Executing automated tests..."
